### ISSUE TITLE
Manage mobs

### ISSUE THREAD

**Issue by edurne85** [edurne85/wowfinder#516]
- [ ] Data structures for scalable profiles
- [ ] Data structures for custom mobs 
- [ ] UI / views for scalable profiles
- [ ] Loot table management
- [ ] UI / views for mobs (scaled and custom)
