### ISSUE TITLE
Full Spell dump

### ISSUE THREAD

**Issue by edurne85** [edurne85/wowfinder#522]
We need the full range of spells available to players implemented in the app. Initial implementation should include asset files as well as localized texts for at least one language, but by Beta stage we should have all texts available in every supported language.

The dump is split on several tasks to make things more manageable (mostly by alphabetical names in Spanish):

- [ ] #502 (15 initial spells)
- [ ] C / D: Magic Fang, Command Undead, Shocking Grasp, Cure Wounds, Mass Cure Wounds, Detect Magic, Disguise
- [ ] E / F: Shield, Flaming Sphere, Eagle's Splendor, False Life, Acid Arrow, Faerie Fire, Bull's Strength
- [ ] G - I: Shillelagh, Cat's Grace, Image (Minor, Major), True Strike, Inflict Wounds, Mass Inflict Wounds, Necrotic Inspiration (TBC)
- [ ] M - P: Burning Hands, Guidance, Disturb Undead, Prestidigitation, Protection from Alignment, Magic Missile
- [ ] R: Ray of Enfeeblement, Mending, Bear's Endurance, Resist Energy, Expeditious Retreat
- [ ] S - Z: Owl's Wisdom, Chill Touch, Vampiric Touch, Virtue, Longstrider
- [ ] Additional level 0 spells: TBD
- [ ] Additional level 1 spells: TBD
- [ ] Additional level 2 spells: TBD
- [ ] Additional level 3 spells: TBD
- [ ] Additional level 4 spells: TBD
- [ ] Additional level 5 spells: TBD
- [ ] Additional level 6 spells: TBD
- [ ] Additional level 7 spells: TBD
- [ ] Additional level 8 spells: TBD
- [ ] Additional level 9 spells: TBD
