### ISSUE TITLE
Asset files for trade goods

### ISSUE THREAD

**Issue by edurne85** [edurne85/wowfinder#528]
- [ ] Apprentice tier
- [ ] Journeyman tier
- [ ] Expert tier
- [ ] Artisan tier
- [ ] Master (BC) tier
- [ ] Grand Master (WotLK) tier
- [ ] Illustrious Grand Master (Cata) tier
- [ ] Zen (MoP) tier
- [ ] Draenic (WoD) tier
- [ ] Demonic (Legion) tier
- [ ] BfA tier
- [ ] Shadowlands tier
- [ ] Dragonflight tier

**Comment by edurne85** [comment]
Note: secondary goods (Meat, Fish, Elemental, common / vendor, and possibly others) will be handled on a different ticket.

**Comment by edurne85** [comment]
Marked as paused: first four tiers completed, further ones are not a priority.
