### ISSUE TITLE
Batch 3 (from G to M by Spanish spell name) 

### ISSUE THREAD

**Issue by edurne85** [edurne85/wowfinder#750]
- [x] Shillelagh (see #838)
- [x] Cat's Grace (see #863)
- [x] Image (Minor, Major) (see #881)
- [x] True Strike (see #882)
- [x] Necrotic Inspiration (see #953)
- [x] Burning Hands (see #955)
