### ISSUE TITLE
Crafted gear

### ISSUE THREAD

**Issue by edurne85** [edurne85/wowfinder#864]
### Urgent data entries:
- [x] Tailoring (reinforced linen)
- [x] Blacksmithing (reinforced copper armor)
- [x] #865
- [x] #866

#### Apprentice tier
- [ ] Apprentice Alchemy
- [ ] Apprentice Blacksmithing
- [ ] Apprentice Cooking
- [ ] Apprentice Inscription
- [ ] Apprentice Jewelcrafting
- [ ] Apprentice Leatherworking
- [ ] Apprentice Tailoring
- [ ] Apprentice Technology
- [ ] Apprentice Woodworking
- [ ] Apprentice Enchantment
#### Journeyman tier
- [ ] Journeyman Alchemy
- [ ] Journeyman Blacksmithing
- [ ] Journeyman Cooking
- [ ] Journeyman Inscription
- [ ] Journeyman Jewelcrafting
- [ ] Journeyman Leatherworking
- [ ] Journeyman Tailoring
- [ ] Journeyman Technology
- [ ] Journeyman Woodworking
- [ ] Journeyman Enchantment
#### Expert tier
- [ ] Expert Alchemy
- [ ] Expert Blacksmithing
- [ ] Expert Cooking
- [ ] Expert Inscription
- [ ] Expert Jewelcrafting
- [ ] Expert Leatherworking
- [ ] Expert Tailoring
- [ ] Expert Technology
- [ ] Expert Woodworking
- [ ] Expert Enchantment
#### Artisan tier
- [ ] Artisan Alchemy
- [ ] Artisan Blacksmithing
- [ ] Artisan Cooking
- [ ] Artisan Inscription
- [ ] Artisan Jewelcrafting
- [ ] Artisan Leatherworking
- [ ] Artisan Tailoring
- [ ] Artisan Technology
- [ ] Artisan Woodworking
- [ ] Artisan Enchantment
#### Master tier (TBC)
- [ ] Master Alchemy
- [ ] Master Blacksmithing
- [ ] Master Cooking
- [ ] Master Inscription
- [ ] Master Jewelcrafting
- [ ] Master Leatherworking
- [ ] Master Tailoring
- [ ] Master Technology
- [ ] Master Woodworking
- [ ] Master Enchantment
#### Grand Master tier (WotLK)
- [ ] Grand Master Alchemy
- [ ] Grand Master Blacksmithing
- [ ] Grand Master Cooking
- [ ] Grand Master Inscription
- [ ] Grand Master Jewelcrafting
- [ ] Grand Master Leatherworking
- [ ] Grand Master Tailoring
- [ ] Grand Master Technology
- [ ] Grand Master Woodworking
- [ ] Grand Master Enchantment
#### Illustrious tier (Cata) 
- [ ] Illustrious Alchemy
- [ ] Illustrious Blacksmithing
- [ ] Illustrious Cooking
- [ ] Illustrious Inscription
- [ ] Illustrious Jewelcrafting
- [ ] Illustrious Leatherworking
- [ ] Illustrious Tailoring
- [ ] Illustrious Technology
- [ ] Illustrious Woodworking
- [ ] Illustrious Enchantment
#### Mystic tier (MoP)
- [ ] Mystic Alchemy
- [ ] Mystic Blacksmithing
- [ ] Mystic Cooking
- [ ] Mystic Inscription
- [ ] Mystic Jewelcrafting
- [ ] Mystic Leatherworking
- [ ] Mystic Tailoring
- [ ] Mystic Technology
- [ ] Mystic Woodworking
- [ ] Mystic Enchantment
#### Draenic tier (WoD)
- [ ] Draenic Alchemy
- [ ] Draenic Blacksmithing
- [ ] Draenic Cooking
- [ ] Draenic Inscription
- [ ] Draenic Jewelcrafting
- [ ] Draenic Leatherworking
- [ ] Draenic Tailoring
- [ ] Draenic Technology
- [ ] Draenic Woodworking
- [ ] Draenic Enchantment
#### Demonic tier (Leg)
- [ ] Demonic Alchemy
- [ ] Demonic Blacksmithing
- [ ] Demonic Cooking
- [ ] Demonic Inscription
- [ ] Demonic Jewelcrafting
- [ ] Demonic Leatherworking
- [ ] Demonic Tailoring
- [ ] Demonic Technology
- [ ] Demonic Woodworking
- [ ] Demonic Enchantment
#### Marine tier (BfA)
- [ ] Marine Alchemy
- [ ] Marine Blacksmithing
- [ ] Marine Cooking
- [ ] Marine Inscription
- [ ] Marine Jewelcrafting
- [ ] Marine Leatherworking
- [ ] Marine Tailoring
- [ ] Marine Technology
- [ ] Marine Woodworking
- [ ] Marine Enchantment
#### Shadow tier (SL)
- [ ] Shadow Alchemy
- [ ] Shadow Blacksmithing
- [ ] Shadow Cooking
- [ ] Shadow Inscription
- [ ] Shadow Jewelcrafting
- [ ] Shadow Leatherworking
- [ ] Shadow Tailoring
- [ ] Shadow Technology
- [ ] Shadow Woodworking
- [ ] Shadow Enchantment
#### Draconic tier (DF)
- [ ] Draconic Alchemy
- [ ] Draconic Blacksmithing
- [ ] Draconic Cooking
- [ ] Draconic Inscription
- [ ] Draconic Jewelcrafting
- [ ] Draconic Leatherworking
- [ ] Draconic Tailoring
- [ ] Draconic Technology
- [ ] Draconic Woodworking
- [ ] Draconic Enchantment
#### Earthly tier (TWW)
- [ ] Earthly Alchemy
- [ ] Earthly Blacksmithing
- [ ] Earthly Cooking
- [ ] Earthly Inscription
- [ ] Earthly Jewelcrafting
- [ ] Earthly Leatherworking
- [ ] Earthly Tailoring
- [ ] Earthly Technology
- [ ] Earthly Woodworking
- [ ] Earthly Enchantment
#### Nightly tier (MN)
- [ ] Nightly Alchemy
- [ ] Nightly Blacksmithing
- [ ] Nightly Cooking
- [ ] Nightly Inscription
- [ ] Nightly Jewelcrafting
- [ ] Nightly Leatherworking
- [ ] Nightly Tailoring
- [ ] Nightly Technology
- [ ] Nightly Woodworking
- [ ] Nightly Enchantment
#### Titanic tier (TLT)
- [ ] Titanic Alchemy
- [ ] Titanic Blacksmithing
- [ ] Titanic Cooking
- [ ] Titanic Inscription
- [ ] Titanic Jewelcrafting
- [ ] Titanic Leatherworking
- [ ] Titanic Tailoring
- [ ] Titanic Technology
- [ ] Titanic Woodworking
- [ ] Titanic Enchantment

**Comment by edurne85** [comment]
Migrated to https://github.com/WowFinder/raw-assets/issues/1
